# -*- coding: utf-8 -*-
"""
Generate x32dbg scripts / recipes for automatic plain/cipher logging.

User only needs: attach xajh → run script → set GUI log text once (2020 limits)
→ play → save log → auto_analyze.

@author by ak
"""
from __future__ import annotations

import time
from pathlib import Path
from typing import Any

from packet.crypto_knowledge import (
    ARCFOUR_SETKEY,
    ARCFOUR_UPDATE,
    ARCFOUR_UPDATE_RET,
    CORE_HOOKS,
    IMAGE_BASE,
)


def project_root() -> Path:
    return Path(__file__).resolve().parents[1]


def tools_dir() -> Path:
    return project_root() / "tools"


def packets_dir() -> Path:
    d = project_root() / ".issues" / "packets"
    d.mkdir(parents=True, exist_ok=True)
    return d


def recipe_shot_script() -> str:
    """
    x32dbg 2020 compatible script: set BPs; user fills log text in GUI.

    @author by ak
    """
    u = f"{ARCFOUR_UPDATE:08X}"
    ur = f"{ARCFOUR_UPDATE_RET:08X}"
    sk = f"{ARCFOUR_SETKEY:08X}"
    return f"""// auto-generated by packet/x32dbg_recipes.py — {time.strftime('%Y-%m-%d %H:%M')}
// x32dbg 2020: no logredirect required
// Image base 0x{IMAGE_BASE:08X}
//
// After run: Breakpoints tab → edit each BP:
//   PLAIN @ {u}: Log text = PLAIN {{mem;16@[[esp+4]+4]}}  Fast resume ON
//   SEND10 @ ws2_32.send: pause [esp+0xC]==0xA  Log = SEND10 {{mem;10@[esp+8]}}  Fast resume ON
// Optional UPD_OUT @{ur}: UPD_OUT {{mem;24@[[esp+4]+4]}}
// Then F9 → trigger feature → save log → GUI 封包「分析日志」

log "=== game-get auto plain/cipher logger ==="
log "base=0x{IMAGE_BASE:08X} Update=0x{u} ret=0x{ur} SetKey=0x{sk}"

bp {u}
log "bp Update 0x{u} — GUI: Log text PLAIN {{mem;16@[[esp+4]+4]}}, Fast resume ON, 不输出日志 OFF"

bp ws2_32.send
bpcnd ws2_32.send, [esp+0xC]==0xA
log "bp send len=10 — GUI: Log text SEND10 {{mem;10@[esp+8]}}, Fast resume ON"

// optional return-site (S2C plain / C2S cipher after transform)
bp {ur}
log "bp Update.ret 0x{ur} — GUI: Log text UPD_OUT {{mem;24@[[esp+4]+4]}}, Fast resume ON"

bplist
log "POINT-SHOT: enable BPs -> do action -> disable BPs -> save log to .issues/packets/"
ret
"""


def recipe_plain_only_script() -> str:
    u = f"{ARCFOUR_UPDATE:08X}"
    return f"""// plain-only logger (less noise) — {time.strftime('%Y-%m-%d %H:%M')}
log "=== PLAIN only @ Update 0x{u} ==="
bp {u}
log "GUI: Log text PLAIN {{mem;16@[[esp+4]+4]}}, Fast resume ON"
bplist
ret
"""


def recipe_checklist_md() -> str:
    lines = [
        "# x32dbg 一次配置清单（之后只看日志）",
        "",
        "> 完整说明（含【需你】/【自动】标记）：[docs/PACKET_AUTO_ANALYZE.md](../../docs/PACKET_AUTO_ANALYZE.md)",
        "",
        f"生成时间: {time.strftime('%Y-%m-%d %H:%M')}",
        f"映像基址: `0x{IMAGE_BASE:08X}`",
        "",
        "## 图例",
        "",
        "- **【需你】**：必须你操作",
        "- **【一次】**：通常只做一遍",
        "- **【自动】**：工具完成",
        "- **【只看】**：读结果即可",
        "",
        "## 目标",
        "",
        "配置完成后：**【需你】触发功能 → 【需你】保存日志 → 【需你】点分析**；"
        "配对/壳识别/报告均为 **【自动】**。",
        "",
        "## 步骤（标了【需你】的必须你做）",
        "",
        "1. **【需你】** 管理员运行 x32dbg，附加正在玩的 `xajh.exe`，F9。",
        "2. **【需你】** Script → 加载 `tools/x32dbg_auto_plain_cipher.txt`（脚本文件由工具【自动】生成）。",
        "3. **【需你】** 在脚本第一行点一下，按 **Space** 执行到 `ret`。",
        "4. **【需你】【一次】** **断点** 页按表配置日志（2020 必须手填一次）：",
        "",
        "| 断点 | 暂停条件 | 日志文本 | 快速恢复 | 不输出日志 |",
        "|------|----------|----------|----------|------------|",
    ]
    for h in CORE_HOOKS:
        if h.tag in ("SEND_W",):
            continue
        bp = f"`0x{h.va:08X}`" if h.va else "`ws2_32.send`"
        cond = h.pause_cond or "（空）"
        logt = h.log_text or "—"
        lines.append(f"| {bp} `{h.tag}` | `{cond}` | `{logt}` | **勾** | **不要勾** |")
    lines.extend(
        [
            "",
            "5. **【可选】** 禁用嘈杂旧断点（如裸 `DB0CC2`）。",
            "6. **【需你】** F9 游戏内触发目标功能 1～3 次，并确认功能成功。",
            "7. **【需你】** 日志另存到 `.issues/packets/x32dbg_runtime.log`（或任意路径）。",
            "8. **【需你】** 开发面板 **封包** → **分析日志**（点一下）。",
            "9. **【自动】** 解析 / 配对 / 写报告；**【只看】** 结论与明文密文表。",
            "",
            "## 日志标签速查",
            "",
            "| 标签 | 是什么 |",
            "|------|--------|",
            "| `PLAIN` | Update 入口 → **出站明文**（入站则是密文） |",
            "| `SEND10` | send len=10 → **网络密文** |",
            "| `UPD_OUT` | Update 返回 → 出站密文 / 入站明文 |",
            "",
            "同明文不同密文 = RC4 正常，不要逆推单包密文。",
            "",
            "## 最小必做（全是【需你】）",
            "",
            "```text",
            "[ ] 附加 xajh + 加载脚本",
            "[ ] 【一次】填 PLAIN / SEND10 日志文本",
            "[ ] 触发功能并确认成功",
            "[ ] 保存日志",
            "[ ] 点「分析日志」",
            "```",
            "",
        ]
    )
    return "\n".join(lines)


def write_recipes(out_tools: Path | None = None, out_issues: Path | None = None) -> dict[str, str]:
    """
    Write script + checklist files. Returns path map.

    @author by ak
    """
    td = out_tools or tools_dir()
    pd = out_issues or packets_dir()
    td.mkdir(parents=True, exist_ok=True)
    pd.mkdir(parents=True, exist_ok=True)

    paths: dict[str, str] = {}
    shot = td / "x32dbg_auto_plain_cipher.txt"
    plain = td / "x32dbg_auto_plain_only.txt"
    check = pd / "X32DBG_ONCE_SETUP.md"
    shot.write_text(recipe_shot_script(), encoding="utf-8")
    plain.write_text(recipe_plain_only_script(), encoding="utf-8")
    check.write_text(recipe_checklist_md(), encoding="utf-8")
    # also refresh legacy thin scripts with consistent content
    (td / "x32dbg_log_plain_update.txt").write_text(recipe_plain_only_script(), encoding="utf-8")
    paths["shot_script"] = str(shot)
    paths["plain_script"] = str(plain)
    paths["checklist"] = str(check)
    return paths


def recipe_dict() -> dict[str, Any]:
    return {
        "image_base": f"0x{IMAGE_BASE:08X}",
        "update": f"0x{ARCFOUR_UPDATE:08X}",
        "update_ret": f"0x{ARCFOUR_UPDATE_RET:08X}",
        "setkey": f"0x{ARCFOUR_SETKEY:08X}",
        "hooks": [h.as_dict() for h in CORE_HOOKS],
        "scripts": {
            "plain_cipher": "tools/x32dbg_auto_plain_cipher.txt",
            "plain_only": "tools/x32dbg_auto_plain_only.txt",
        },
    }
