# -*- coding: utf-8 -*-
"""
Write packaging artifacts without putting secrets in plain JSON.

- build_profile.json: channel / URLs / dev captcha key only (no license secret)
- app/core/_pack_secret.py: HMAC secret embedded (xor-obfuscated, gitignored)

Usage:
  python tools/_write_build_profile.py prod
  python tools/_write_build_profile.py dev

@author by ak
"""
from __future__ import annotations

import json
import os
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))

from common.dotenv_load import load_dotenv  # noqa: E402

OUT_PROFILE = Path(
    os.environ.get("XAJH_BUILD_PROFILE_PATH")
    or ROOT / "build" / "generated" / "app" / "data" / "build_profile.json"
)
OUT_PACK_SECRET = Path(
    os.environ.get("XAJH_PACK_SECRET_PATH")
    or ROOT / "app" / "core" / "_pack_secret.py"
)
_DEFAULT_CAPTCHA_BASE_URL = "https://xiaoao.joini.cloud"
_DEFAULT_LICENSE_BASE_URL = "https://xiaoao.joini.cloud"


def _captcha_base_url() -> str:
    """Env / .env override, else built-in default."""
    return (
        str(os.environ.get("XAJH_CAPTCHA_BASE_URL") or "").strip().rstrip("/")
        or _DEFAULT_CAPTCHA_BASE_URL
    )


def _license_base_url(captcha_url: str = "") -> str:
    """Env override, else same host as captcha/service base, else default."""
    return (
        str(os.environ.get("XAJH_LICENSE_BASE_URL") or "").strip().rstrip("/")
        or str(captcha_url or "").strip().rstrip("/")
        or _DEFAULT_LICENSE_BASE_URL
    )


def _license_api_secret() -> str:
    """Shared HMAC secret (must match server LICENSE_API_SECRET). Build-time only."""
    return (
        str(os.environ.get("XAJH_LICENSE_API_SECRET") or "").strip()
        or str(os.environ.get("LICENSE_API_SECRET") or "").strip()
    )


def _write_pack_secret(secret: str, path: Path) -> None:
    """
    Write obfuscated secret module for frozen/source import.

    Not strong crypto — just avoid plain JSON / plain string dumps.
    @author by ak
    """
    raw = (secret or "").encode("utf-8")
    seed = 0x5A
    blob = bytes((b ^ ((seed + i * 13) & 0xFF)) for i, b in enumerate(raw))
    ints = ", ".join(str(x) for x in blob)
    lines = [
        "# -*- coding: utf-8 -*-",
        '"""',
        "AUTO-GENERATED by tools/_write_build_profile.py — do not commit real secrets.",
        "",
        "Package-embedded LICENSE HMAC material. Runtime: app.core.build_profile.",
        "@author by ak",
        '"""',
        "from __future__ import annotations",
        "",
        "# xor-obfuscated utf-8 (not encryption; keeps secrets out of build_profile.json)",
        f"_BLOB = bytes([{ints}])",
        f"_SEED = {seed}",
        "",
        "",
        "def license_api_secret() -> str:",
        '    """Decode pack-time LICENSE_API_SECRET. Empty if build had no secret."""',
        "    if not _BLOB:",
        '        return ""',
        "    try:",
        "        raw = bytes((b ^ ((_SEED + i * 13) & 0xFF)) for i, b in enumerate(_BLOB))",
        '        return raw.decode("utf-8")',
        "    except Exception:",
        '        return ""',
        "",
    ]
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text("\n".join(lines) + "\n", encoding="utf-8")


def main(argv: list[str]) -> int:
    """
    Write build profile JSON (no secrets) + embedded pack secret module.

    @author by ak
    """
    load_dotenv(ROOT / ".env", only_if_unfrozen=False)
    ch = (argv[1] if len(argv) > 1 else "prod").strip().lower()
    base_url = _captcha_base_url()
    license_url = _license_base_url(base_url)
    license_secret = _license_api_secret()
    if ch in ("dev", "test"):
        data = {
            "channel": "dev",
            "debug_default": True,
            "captcha_base_url": base_url,
            "license_base_url": license_url,
            "captcha_api_key": str(os.environ.get("XAJH_CAPTCHA_API_KEY") or "").strip(),
        }
    elif ch in ("prod", "production", "release", ""):
        data = {
            "channel": "prod",
            "debug_default": False,
            "captcha_base_url": base_url,
            "license_base_url": license_url,
            "captcha_api_key": "",
        }
    else:
        print(f"unknown channel: {ch!r} (use dev|prod)")
        return 2

    OUT_PROFILE.parent.mkdir(parents=True, exist_ok=True)
    OUT_PROFILE.write_text(
        json.dumps(data, ensure_ascii=False, indent=2) + "\n",
        encoding="utf-8",
    )
    _write_pack_secret(license_secret, OUT_PACK_SECRET)
    gen_copy = ROOT / "build" / "generated" / "app" / "core" / "_pack_secret.py"
    if gen_copy.resolve() != OUT_PACK_SECRET.resolve():
        _write_pack_secret(license_secret, gen_copy)

    print(f"wrote {OUT_PROFILE}")
    print(f"wrote {OUT_PACK_SECRET} (embedded secret, not JSON)")
    key = str(data.get("captcha_api_key") or "")
    print(
        json.dumps(
            {
                "channel": data["channel"],
                "debug_default": data["debug_default"],
                "captcha_base_url": data["captcha_base_url"],
                "license_base_url": data["license_base_url"],
                "license_secret_embedded": bool(license_secret),
                "license_secret_len": len(license_secret),
                "captcha_key_set": bool(key),
                "captcha_key_len": len(key),
                "json_has_license_secret": "license_api_secret" in data,
            },
            ensure_ascii=False,
        )
    )
    if not license_secret:
        print("WARNING: LICENSE_API_SECRET empty — packaged client cannot sign")
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv))
